-- Internity DB schema (no authentication)
-- Identity = anonymous_id generated by extension

-- Dev reset (remove in production)
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS jobs CASCADE;

-- UUID support
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ===========================================
-- JOBS TABLE (scraped + LLM-enriched)
-- ===========================================
CREATE TABLE jobs (
  id SERIAL PRIMARY KEY,

  source VARCHAR(50) NOT NULL,              -- linkedin / indeed / etc.
  job_url TEXT NOT NULL UNIQUE,             -- dedupe key

  title VARCHAR(500) NOT NULL,
  company VARCHAR(200),
  location VARCHAR(200),
  description TEXT,

  -- LLM extracted fields
  skills JSONB DEFAULT '[]'::jsonb,          -- array of strings
  responsibilities JSONB DEFAULT '[]'::jsonb,-- array of strings
  role_category VARCHAR(100),                -- frontend/backend/data/etc.
  seniority VARCHAR(50),                     -- intern/newgrad/junior/...
  work_style JSONB DEFAULT '[]'::jsonb,       -- ["remote","hybrid"] etc.

  metadata JSONB DEFAULT '{}'::jsonb,         -- raw scraper fields, salary, etc.

  scraped_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for filtering/search
CREATE INDEX idx_jobs_source ON jobs(source);
CREATE INDEX idx_jobs_company ON jobs(company);
CREATE INDEX idx_jobs_location ON jobs(location);
CREATE INDEX idx_jobs_scraped_at ON jobs(scraped_at DESC);

-- JSON indexes (fast skill / metadata queries)
CREATE INDEX idx_jobs_skills_gin ON jobs USING GIN(skills);
CREATE INDEX idx_jobs_metadata_gin ON jobs USING GIN(metadata);

-- ===========================================
-- EVENTS TABLE (behavior tracking)
-- ===========================================
CREATE TABLE events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  anonymous_id UUID NOT NULL,                -- stored in chrome.storage.local
  event_type VARCHAR(50) NOT NULL CHECK (
    event_type IN (
      'job_viewed',
      'job_saved',
      'job_applied',
      'job_skipped',
      'recommendation_feedback'
    )
  ),

  job_id INTEGER REFERENCES jobs(id) ON DELETE SET NULL,
  job_url TEXT NOT NULL,                     -- keep url even if job missing

  -- behavior signals
  dwell_time_ms INTEGER,                     -- time on posting
  scroll_depth NUMERIC(5,2),                 -- 0-100
  revisit_count INTEGER DEFAULT 0,

  metadata JSONB DEFAULT '{}'::jsonb,         -- anything else
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for analytics + recommendations
CREATE INDEX idx_events_anon ON events(anonymous_id);
CREATE INDEX idx_events_type ON events(event_type);
CREATE INDEX idx_events_created ON events(created_at DESC);
CREATE INDEX idx_events_job_url ON events(job_url);
CREATE INDEX idx_events_anon_type_created ON events(anonymous_id, event_type, created_at DESC);
CREATE INDEX idx_events_metadata_gin ON events USING GIN(metadata);

-- Prevent spam duplicates for same user+job+type in short time (optional)
-- You can enforce uniqueness if you want, but it can be too strict for views:
-- CREATE UNIQUE INDEX uniq_apply_per_job ON events(anonymous_id, job_url, event_type)
-- WHERE event_type = 'job_applied';
